### ISSUE TITLE
`clockify-cli out` command is throwing `Nothing was found (code: 404)

### ISSUE THREAD

**Issue by lockHrt** [lucassabreu/clockify-cli#130] opened 2021-09-20 09:22 UTC
Hi,
Just moved from v0.22.0 to v0.24.0. I have been able to start new time entry using `clockify-cli in` but when I use `clockify-cli out` it says 'Nothing was found (code: 404)' and the entry keeps running (when checked from the website). If I stop it from the clockify website and then use the command `clockify-cli out` again then it says 'no time entry in progress' (which is correct this time)

So,
Time entry in progress -> `clockify out` -> `Nothing was found (code: 404)`
Time entry not in progress -> `clockify out` -> `no time entry in progress`

I'm using it on windows 10 (powershell). Earlier `clockify-cli out` worked fine on v0.22.0 

Thanks for adding support for tasks.

**Comment by lucassabreu** [comment] 2021-09-20 11:05
duplicate of #129, but thank for the extra information

**Closed by lucassabreu** 2021-09-20 11:05 UTC
